.\"
.\" Copyright (c) 2015-2017 Tobias Kortkamp <t@tobik.me>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\" SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
.\" OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
.\" CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd July 24, 2017
.Dt PATMAT 1
.Os
.Sh NAME
.Nm patmat
.Nd "a pattern matching tool"
.Sh SYNOPSIS
.Nm
.Fl p Ar pattern
.Op Fl c Ar command
.Op Fl i
.Op Fl f Ar separator
.Op Fl t Ar format
.Op Fl v
.Op Ar string ...
.Sh DESCRIPTION
.Nm
is a small tool for matching strings.
The
.Ar pattern
is tried on each string and if there is a match
.Ar command
is executed with the original string and a string that is created from
.Ar format .
.Pp
.Nm
will match on lines read from stdin if no string arguments are passed
to it.
.Sh OPTIONS
.Bl -tag -width ".Cm command"
.It Fl p Ar pattern
The patterns used for matching.
See
.Xr patmat-patterns 7
for details on the
pattern language.
.It Fl c Ar script
The script to execute when
.Ar pattern
matches a string.
.Ar script
is passed to
.Pa /bin/sh .
In the script the matching string (source) and a new string
constructed out of the target format will be available as $1 and $2
respectively.
.Pp
If
.Fl c
is not specified, the source and target will be printed to stdout
separated by a tab (\\t) or the string specified with
.Fl f .
.It Fl f
Set to change the string used as separator for source and target.
By default a tab is used.  This option is ignored when
.Fl c
is used.
.It Fl i
Ignore errors encountered while running
.Ar script .
By default
.Nm
will terminate when the script fails to run.
This option is ignored when
.Fl c
is not used.
.It Fl t Ar format
Target format.
\fB%n\fP will be replaced by the n-th capture from the pattern.
Defaults to \fB%0\fP i.e. the whole matching string.
.It Fl v
Warn on encountering non matching arguments.
.El
.Sh EXAMPLES
Rename all files like '123 - foo.jpg' to 'foo.jpg' in the current directory
.Bd -literal -offset indent
patmat -p '%d+% %-% ([%a%p]+)' -t %1 -c 'mv "$1" "$2"' *
.Ed
.Pp
\fB%1\fP is replaced by the first capture defined by the parentheses
in the pattern.
.Pp
Output a CSV table with two columns: The first column will have the
original filenames and the second column will have the filenames with
a 'FreeBSD-' prefix and '.iso' suffix for all files in the current
directory.
.Bd -literal -offset ident
patmat -p '.*' -f';' -t 'FreeBSD-%0.iso' * > out.csv
.Ed
.Pp
.Sh SEE ALSO
.Xr patmat-patterns 7
.Sh AUTHORS
.An Tobias Kortkamp Aq Mt t@tobik.me
.Pp
.Nm
uses the pattern matching engine from OpenBSD's httpd, which does all
the hard work and is derived from the original implementation of the
Lua scripting language written by
.An -nosplit
.An Roberto Ierusalimschy ,
.An Waldemar Celes ,
and
.An Luiz Henrique de Figueiredo
at PUC-Rio.
It was turned into a native C API for
.Xr httpd 8
by
.An Reyk Floeter Aq Mt reyk@openbsd.org .
